### ISSUE TITLE
visualization issues

### ISSUE THREAD

**Issue by eu-genia** [SChAth/ScAthiop#157]
- [x] font size for H1/2/3 should be reduced (everything should become more compact)
- [x] also in relations/timeline and elsewhere transcription ("normalized") should be shown instead of fidel when available
- [x] some of navigation does not work (Bibl. under Works e.g.)
- [x] we do not need the [normalized] bracket to be shown in links (s. e.g. LIT3949MashafaKrL: "The long version agrees with the short versions Maṣḥafa krǝstǝnnā [normalized] ")
- [x] is it possible to make relation graphs clickable?

MSS
- [x]  "Writing material" should be moved under "Physical description"
- [x]  "Summary" - should be moved up (after Number of codicological units, before Origin)
In the summary if possible subparts should be indented
- [x]  Layout: units (mm) should be added to Margins
- [x]  Layout: still errors are signalled in red ("the following values are recognized as empty: right margin" - the margin is not empty)
- [x]  Scribe: the name appears twice

WORK
- [x]  divs describing text parts are not visualized
- [x]  mss mentioning the work should appear 1xeach (even if a ms contains several parts of a work)
- [x]  all titles should appear as it has been done for persons: Fidel (Transcription, Translation)

PERSON
- [x]  the titles often do not appear in the list and also in the single entry even though they are there in the XML - e.g. PRS10775Trinity
- [x]  the persName links are not visualized as active links (s. e.g. PRS4428Galawdew: "His reign was marked by a successful struggle against <persName corresp="PRS1522Ahmadb">Aḥmad b. Ibrāhīm al-Ġāzī</persName>")

(NB for some reason I discovered that some files have been overwritten with earlier versions (?), e.g. Trinity - my version of 9.5. has been replaced by the original stub, now retrieved, but should not happen?)

**Comment by eu-genia** [comment]
@MassimoVilla @thea-m @sologebre have i forgotten anything?

**Comment by thea-m** [comment]
Not sure if this is the reason for the PersName links, but there was a small mistake in PRS4428Galawdew, still using corresp instead of ref in PersName...I corrected it to ` <persName ref="PRS1522Ahmadb">Aḥmad b. Ibrāhīm al-Ġāzī</persName>` and the link is now correctly displayed in the preview, but still not on the webpage

**Comment by PietroLiuzzo** [comment]
The titles in persons list might still appear wrong in cases where there is no pr
